### ISSUE TITLE
Bug : key_words in the log_cli.py

### ISSUE THREAD

**Issue by Abhi001vj** [arita37/mlmodels#360]
I will work on correcting keywords errors like this

https://github.com/arita37/mlmodels_store/blob/master/log_test_cli/log_cli.py#L647

 ```
********************************************************************************************************************************************
ml_optim --do search  --config_file template/optim_config.json  --config_mode "test"  2>&1 | tee -a  cd log_cli_$(date +%Y-%m-%d_%H).txt
Deprecaton set to False

  ############# OPTIMIZATION Start  ############### 
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.10/x64/bin/ml_optim", line 11, in <module>
    load_entry_point('mlmodels', 'console_scripts', 'ml_optim')()
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 388, in main
    optim_cli(arg)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 259, in optim_cli
    out_pars        = out_pars )
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 54, in optim
    if hypermodel_pars["engine_pars"]['engine'] == "optuna":
KeyError: 'engine_pars'

```

**Comment by Abhi001vj** [comment]
The json file is not properly formatted, it is missing the engine parameters  "engine_pars" inside the "hypermodel_pars"

**Comment by Abhi001vj** [comment]
The loss function name was missing and it is stated as just loss in the model.stats https://github.com/arita37/mlmodels/blob/108f32ed4ae14656a64508718e972383b4407da0/mlmodels/model_tf/1_lstm.py#L59

**Comment by Abhi001vj** [comment]
FIX https://github.com/arita37/mlmodels/pull/366
